/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Dashboard;
import model.ToolDashboard;
import model.database.DBException;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.JComboBox;
import model.DashboardItem;

/**
 *
 * @author mju
 */
public class FrameDashboard extends javax.swing.JFrame {

    ToolDashboard toolDashboard;
    ArrayList<Dashboard> listDashboard;
    ArrayList<DashboardItem> listDashboardItems;
    Dashboard dashboard;
    DashboardItem dashboardItem;
    Integer correct=0;
    Integer total=0;
    Integer percent;
    float fPercent;
    String subject;
    


    public FrameDashboard(String username) throws DBException {

        toolDashboard=new ToolDashboard(username);
        listDashboard=toolDashboard.getListDashboard();
        
        initComponents();
        setVisible(true);        

        //jComboBoxLevel.addItem("k1-practice");
        //jComboBoxLevel.addItem("k1-test");
        //jComboBoxLevel.addItem("23-practice");
        //jComboBoxLevel.addItem("23-test");
        jComboBoxLevel.setSelectedIndex(0);
        

        dashboard=listDashboard.get(0);
        listDashboardItems=dashboard.getListDashboardItems();


        dashboardItem=listDashboardItems.get(0);
        correct=dashboardItem.getCorrect();
        total=dashboardItem.getTotal();
        subject=dashboardItem.getSubject();
                    
        if(total>0){
           fPercent=(correct.floatValue()/total.floatValue())*100;
        }

        jLabelSubject1.setText(subject);
        jLabelSubject1Correct.setText(Integer.toString(correct));
        jLabelSubject1Total.setText(Integer.toString(total));
        jLabelSubject1Percent.setText(String.valueOf(fPercent));


        dashboardItem=listDashboardItems.get(1);
        correct=dashboardItem.getCorrect();
        total=dashboardItem.getTotal();
        subject=dashboardItem.getSubject();

        if(total>0){
            fPercent=(correct.floatValue()/total.floatValue())*100;
        }

        jLabelSubject2.setText(subject);
        jLabelSubject2Correct.setText(Integer.toString(correct));
        jLabelSubject2Total.setText(Integer.toString(total));
        jLabelSubject2Percent.setText(String.valueOf(fPercent));



        jComboBoxLevel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(Objects.requireNonNull(jComboBoxLevel.getSelectedItem()).toString().equals("k1-practice")){
                    
                    dashboard=listDashboard.get(0);
                    listDashboardItems=dashboard.getListDashboardItems();                   
                    dashboardItem=listDashboardItems.get(0);
                    
                    correct=dashboardItem.getCorrect();
                    total=dashboardItem.getTotal();
                    subject=dashboardItem.getSubject();
                    
                    if(total>0){
                        fPercent=(correct.floatValue()/total.floatValue())*100;
                    }

                    jLabelSubject1.setText(subject);
                    jLabelSubject1Correct.setText(Integer.toString(correct));
                    jLabelSubject1Total.setText(Integer.toString(total));
                    jLabelSubject1Percent.setText(String.valueOf(fPercent));                   
                    
                    

                }
                
            }
            
        });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSubject1 = new javax.swing.JLabel();
        jLabelSubject2 = new javax.swing.JLabel();
        jLabelSubject3 = new javax.swing.JLabel();
        jLabelSubject1Correct = new javax.swing.JLabel();
        jLabelSubject2Correct = new javax.swing.JLabel();
        jLabelSubject3Correct = new javax.swing.JLabel();
        jLabelSubject1Total = new javax.swing.JLabel();
        jLabelSubject2Total = new javax.swing.JLabel();
        jLabelSubject3Total = new javax.swing.JLabel();
        jLabelCorrect = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelSubject1Percent = new javax.swing.JLabel();
        jLabelSubject2Percent = new javax.swing.JLabel();
        jLabelSubject3Percent = new javax.swing.JLabel();
        jLabelPercent = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jComboBoxLevel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabelSubject1.setText("jLabel1");

        jLabelSubject2.setText("jLabel1");

        jLabelSubject3.setText("jLabel1");

        jLabelSubject1Correct.setText("jLabel1");

        jLabelSubject2Correct.setText("jLabel1");

        jLabelSubject3Correct.setText("jLabel1");

        jLabelSubject1Total.setText("jLabel1");

        jLabelSubject2Total.setText("jLabel1");

        jLabelSubject3Total.setText("jLabel1");

        jLabelCorrect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCorrect.setText("correct");

        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotal.setText("total");

        jLabelSubject1Percent.setText("jLabel1");

        jLabelSubject2Percent.setText("jLabel1");

        jLabelSubject3Percent.setText("jLabel1");

        jLabelPercent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPercent.setText("%");

        jButtonBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBack.setMaximumSize(new java.awt.Dimension(120, 80));

        jComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "k1-practice", "k1-test", "23-practice", "23-test" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSubject2Correct, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSubject3Correct, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelSubject2Total, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSubject3Total, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(jLabelSubject1Correct, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSubject1Total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSubject1Percent, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelSubject2Percent, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSubject3Percent, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSubject1Percent, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelSubject1Correct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelSubject1Total, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSubject2Correct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSubject2Total, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSubject2Percent, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSubject3Correct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSubject3Total, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSubject3Percent, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JComboBox<String> jComboBoxLevel;
    private javax.swing.JLabel jLabelCorrect;
    private javax.swing.JLabel jLabelPercent;
    private javax.swing.JLabel jLabelSubject1;
    private javax.swing.JLabel jLabelSubject1Correct;
    private javax.swing.JLabel jLabelSubject1Percent;
    private javax.swing.JLabel jLabelSubject1Total;
    private javax.swing.JLabel jLabelSubject2;
    private javax.swing.JLabel jLabelSubject2Correct;
    private javax.swing.JLabel jLabelSubject2Percent;
    private javax.swing.JLabel jLabelSubject2Total;
    private javax.swing.JLabel jLabelSubject3;
    private javax.swing.JLabel jLabelSubject3Correct;
    private javax.swing.JLabel jLabelSubject3Percent;
    private javax.swing.JLabel jLabelSubject3Total;
    private javax.swing.JLabel jLabelTotal;
    // End of variables declaration//GEN-END:variables
}
