/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Dashboard;
import model.ToolDashboard;
import model.database.DBException;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.ArrayList;
import java.util.Objects;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import model.DashboardItem;
import model.ImageReference;
import model.ToolImage;
import view.login.FrameLogin;

/**
 *
 * @author mju
 */
public class FrameDashboard extends javax.swing.JFrame {

    ToolDashboard toolDashboard;
    ArrayList<Dashboard> listDashboard;
    ArrayList<DashboardItem> listDashboardItems;
    Dashboard dashboard;
    DashboardItem dashboardItem;
    Integer correct=0;
    Integer total=0;
    Integer percent;
    float fPercent;
    String subject;
    ToolImage toolImage;
    ImageIcon imageIcon;

    public FrameDashboard(String username) throws DBException {

        toolDashboard=new ToolDashboard(username);
        listDashboard=toolDashboard.getListDashboard();
        
        initComponents();
        setVisible(true);    
        
        //load image
        try {
            toolImage = new ToolImage();
            for (ImageReference imageRef : toolImage.getListImageReference()) {
                
                //one if statement for one image
                if (imageRef.getImageName().equals("background-plain-1280x720.png")) {
                    imageIcon = new ImageIcon(ImageIO.read(new URL(imageRef.getStrUrl())));
                    jLabelBackground.setIcon(imageIcon);
                }
                if (imageRef.getImageName().equals("back-120x80.jpg")) {
                    imageIcon = new ImageIcon(ImageIO.read(new URL(imageRef.getStrUrl())));
                    jButtonBack.setIcon(imageIcon);
                }
                
            }
        }
        catch (Exception ex)
        {

        }

        //jComboBoxLevel.addItem("k1-practice");
        //jComboBoxLevel.addItem("k1-test");
        //jComboBoxLevel.addItem("23-practice");
        //jComboBoxLevel.addItem("23-test");
        //jComboBoxLevel.setSelectedIndex(0);
        

        dashboard=listDashboard.get(0);
        listDashboardItems=dashboard.getListDashboardItems();
        dashboardItem=listDashboardItems.get(0);
        correct=dashboardItem.getCorrect();
        total=dashboardItem.getTotal();
        subject=dashboardItem.getSubject();
                    
        if(total>0){
           fPercent=(correct.floatValue()/total.floatValue())*100;
        }

        jLabelSubject1.setText(subject);
        jLabelSubject1Correct.setText(Integer.toString(correct));
        jLabelSubject1Total.setText(Integer.toString(total));
        jLabelSubject1Percent.setText(String.valueOf(fPercent));


        dashboardItem=listDashboardItems.get(1);
        correct=dashboardItem.getCorrect();
        total=dashboardItem.getTotal();
        subject=dashboardItem.getSubject();

        if(total>0){
            fPercent=(correct.floatValue()/total.floatValue())*100;
        }

        jLabelSubject2.setText(subject);
        jLabelSubject2Correct.setText(Integer.toString(correct));
        jLabelSubject2Total.setText(Integer.toString(total));
        jLabelSubject2Percent.setText(String.valueOf(fPercent));
        
        jButtonBack.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FrameHome frameHome=new FrameHome(username);
                dispose(); 
            }
        });  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSubject1 = new javax.swing.JLabel();
        jLabelSubject2 = new javax.swing.JLabel();
        jLabelSubject3 = new javax.swing.JLabel();
        jLabelSubject1Correct = new javax.swing.JLabel();
        jLabelSubject2Correct = new javax.swing.JLabel();
        jLabelSubject3Correct = new javax.swing.JLabel();
        jLabelSubject1Total = new javax.swing.JLabel();
        jLabelSubject2Total = new javax.swing.JLabel();
        jLabelSubject3Total = new javax.swing.JLabel();
        jLabelCorrect = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelSubject1Percent = new javax.swing.JLabel();
        jLabelSubject2Percent = new javax.swing.JLabel();
        jLabelSubject3Percent = new javax.swing.JLabel();
        jLabelPercent = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSubject1.setText("jLabel1");
        getContentPane().add(jLabelSubject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 191, 123, 42));

        jLabelSubject2.setText("jLabel1");
        getContentPane().add(jLabelSubject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 310, 123, 42));

        jLabelSubject3.setText("jLabel1");
        getContentPane().add(jLabelSubject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 420, 123, 42));

        jLabelSubject1Correct.setText("jLabel1");
        getContentPane().add(jLabelSubject1Correct, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 191, 87, 42));

        jLabelSubject2Correct.setText("jLabel1");
        getContentPane().add(jLabelSubject2Correct, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 310, 87, 42));

        jLabelSubject3Correct.setText("jLabel1");
        getContentPane().add(jLabelSubject3Correct, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 420, 87, 42));

        jLabelSubject1Total.setText("jLabel1");
        getContentPane().add(jLabelSubject1Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 191, 87, 42));

        jLabelSubject2Total.setText("jLabel1");
        getContentPane().add(jLabelSubject2Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 310, 87, 42));

        jLabelSubject3Total.setText("jLabel1");
        getContentPane().add(jLabelSubject3Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 420, 87, 42));

        jLabelCorrect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCorrect.setText("correct");
        getContentPane().add(jLabelCorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 131, 87, 42));

        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotal.setText("total");
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 131, 87, 42));

        jLabelSubject1Percent.setText("jLabel1");
        getContentPane().add(jLabelSubject1Percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 191, 87, 42));

        jLabelSubject2Percent.setText("jLabel1");
        getContentPane().add(jLabelSubject2Percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 310, 87, 42));

        jLabelSubject3Percent.setText("jLabel1");
        getContentPane().add(jLabelSubject3Percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 420, 87, 42));

        jLabelPercent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPercent.setText("%");
        getContentPane().add(jLabelPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 131, 87, 42));

        jButtonBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBack.setMaximumSize(new java.awt.Dimension(120, 80));
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 26, 80, 120));

        jLabelBackground.setText("background-test.jpg");
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCorrect;
    private javax.swing.JLabel jLabelPercent;
    private javax.swing.JLabel jLabelSubject1;
    private javax.swing.JLabel jLabelSubject1Correct;
    private javax.swing.JLabel jLabelSubject1Percent;
    private javax.swing.JLabel jLabelSubject1Total;
    private javax.swing.JLabel jLabelSubject2;
    private javax.swing.JLabel jLabelSubject2Correct;
    private javax.swing.JLabel jLabelSubject2Percent;
    private javax.swing.JLabel jLabelSubject2Total;
    private javax.swing.JLabel jLabelSubject3;
    private javax.swing.JLabel jLabelSubject3Correct;
    private javax.swing.JLabel jLabelSubject3Percent;
    private javax.swing.JLabel jLabelSubject3Total;
    private javax.swing.JLabel jLabelTotal;
    // End of variables declaration//GEN-END:variables
}
