/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Cameron
 */
public class Frame4Subject1Menu extends javax.swing.JFrame {

    /**
     * Creates new form Frame23Subject1Menu
     */
    public Frame4Subject1Menu(String userName) {
        initComponents();
        setLocationRelativeTo(null);        
        setVisible(true);
        
        
        jButtonPractice.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
             Frame4Subject1Practice frame4PracticeSubject1=new Frame4Subject1Practice(userName);
                
             dispose(); 
            }
        });
        
        jButtonTest.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
             Frame4Subject1Test frame4TestSubject1=new Frame4Subject1Test(userName);
             
                
             dispose();
            }
        });
        
        jButtonTutorial.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
             Frame4Subject1Tutorial frame4TutorialSubject1=new Frame4Subject1Tutorial(userName);
             
                
             dispose();
            }
        });
        
        jButtonBack.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Frame4Subjects frame4=new Frame4Subjects(userName);
                dispose(); 
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonPractice = new javax.swing.JButton();
        jButtonTest = new javax.swing.JButton();
        jButtonTutorial = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Subject 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jButtonPractice.setText("Practice");
        getContentPane().add(jButtonPractice, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jButtonTest.setText("Test");
        getContentPane().add(jButtonTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));

        jButtonTutorial.setText("Tutorial");
        getContentPane().add(jButtonTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        jButtonBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cameron\\Documents\\MathDiver-main\\src\\main\\java\\view\\images\\Slide1.JPG")); // NOI18N
        jButtonBack.setPreferredSize(new java.awt.Dimension(150, 180));
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cameron\\Documents\\MathDiver-main\\src\\main\\java\\view\\images\\2-3Page.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonPractice;
    private javax.swing.JButton jButtonTest;
    private javax.swing.JButton jButtonTutorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
