/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Cameron
 */
public class Frame23Subject1Test extends javax.swing.JFrame {

    /**
     * Creates new form FrameK1AdditionTest
     */
    public Frame23Subject1Test(String userName) {
        initComponents();
        setLocationRelativeTo(null);        
        setVisible(true);
        
        //ImageIcon icon = new ImageIcon("C:\\Users\\Cameron\\Documents\\MathDiver-main\\src\\main\\java\\view\\images\\Homepage.jpg");
        //jLabel1 = new JLabel(new ImageIcon("C:\\\\Users\\\\Cameron\\\\Documents\\\\MathDiver-main\\\\src\\\\main\\\\java\\\\view\\\\images\\\\Homepage.jpg"));
        
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Frame23Subject1Menu frame23subject1=new Frame23Subject1Menu(userName);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/BackButton.PNG"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(225, 225));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 130, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cameron\\Documents\\MathDiver-main\\src\\main\\java\\view\\images\\Slide2_1.JPG")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
